topic:
  name: customers
  partitions-num: 3
  replication-factor: 1
server:
  port: 9081
spring:
  kafka:
    bootstrap.servers: localhost:9092
    schema.registry.url: http://localhost:8081
    consumer:
      topic: ${topic.name}
      group-id: challenge
      auto-offset-reset: latest
logging:
  level:
    root: info
